#[repr(C)]
#[derive(Debug, PartialEq)]
pub enum PsycRoutingVar {
    PSYC_RVAR_UNKNOWN,

    PSYC_RVAR_AMOUNT_FRAGMENTS,
    PSYC_RVAR_CONTEXT,
    PSYC_RVAR_COUNTER,
    PSYC_RVAR_FRAGMENT,
    PSYC_RVAR_SOURCE,
    PSYC_RVAR_SOURCE_RELAY,
    PSYC_RVAR_TAG,
    PSYC_RVAR_TAG_RELAY,
    PSYC_RVAR_TARGET,
    PSYC_RVAR_TARGET_RELAY,

    PSYC_RVARS_NUM,
}

#[repr(C)]
#[derive(Debug, PartialEq)]
pub enum PsycType {
    PSYC_TYPE_UNKNOWN,
    PSYC_TYPE_AMOUNT,
    PSYC_TYPE_COLOR,
    PSYC_TYPE_COUNTER,
    PSYC_TYPE_DATE,
    PSYC_TYPE_DEGREE,
    PSYC_TYPE_DICT,
    PSYC_TYPE_ENTITY,
    PSYC_TYPE_FLAG,
    PSYC_TYPE_LANGUAGE,
    PSYC_TYPE_LIST,
    PSYC_TYPE_NICK,
    PSYC_TYPE_PAGE,
    PSYC_TYPE_STRUCT,
    PSYC_TYPE_TIME,
    PSYC_TYPE_UNIFORM,
}
